// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsiuafovbxgdybyqhhjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzaXVhZm92YnhnZHlieXFoaGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDUxNDEsImV4cCI6MjA3MDM4MTE0MX0.xyGFAntrOqts41wbKwUCwCvIVsCmKBduzcAwzU7BGn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});